# adapted from https://github.com/openai/simple-evals/blob/main/common.py

system: ""

user: |-
    You will be asked to look at the two answers (predicted and expected) to a math problem and to judge whether they are equivalent within the context of the problem.

    Please first explain your reasoning in a couple of sentences. Then respond with only Yes or No as your judgement on whether the two answers are the same.
    When comparing answers only perform trivial simplifications.

    Here are a few examples.


    Example 1:
    Problem: Factor $7x^3 - 21x^2 + 14x$.
    Predicted answer: $7x(x - 2)(x - 1)$
    Expected answer: $7x(x-1)(x-2)$

    Reasoning: The order of the factors does not matter, so the answers are the same.
    Judgement: Yes


    Example 2:
    Problem: A rectangle has a length of 6 meters and a width of 2 meters. If the length is reduced by 3 meters and the width is halved, what is the new area of the rectangle in square meters?
    Predicted answer: 3/2
    Expected answer: 1.5

    Reasoning: 3/2 is the same as 1.5
    Judgement: Yes


    Example 3:
    Problem: Simplify the expression $\sqrt{{7!}}$, where $n!$ stands for $n\cdot(n-1)\cdot(n-2)\cdots \cdot 2\cdot 1$.
    Predicted answer: 71
    Expected answer: 12\sqrt{{35}}.

    Reasoning: This is non-trivial to simplify, so the answers are different.
    Judgement: No


    Example 4:
    Problem: What is the simplified form of the expression $\sqrt{{98 x^{{3}} y^{{5}} z}} ?
    \begin{{align*}}
    \text{{A)}} & 2 x y z \sqrt{{7 x y z}} &
    \text{{B)}} &  7 x^{{2}} y^{{2}} \sqrt{{2 y z}}
    \\
    \text{{C)}} & 7 x y^{{2}} \sqrt{{2 x y z}}  &
    \text{{D)}} &49 x y^{{2}} \sqrt{{2 x y z}}
    \\
    \end{{align*}}
    Predicted answer: 7 x y^{{2}} \\sqrt{{2 x y z}}
    Expected answer: C

    Reasoning: Predicted answer is the same as the expected answer choice C.
    Judgement: Yes


    Example 5:
    Problem: A line segment of length $5$ has one endpoint at $(1, 2)$ and the other endpoint at $(4, b)$. Find all possible values of $b$, separated by commas.
    Predicted answer:  -2, 6
    Expected answer: 6, -2

    Reasoning: The order doesn't matter in the context of the problem.
    Judgement: Yes


    Example 6:
    Problem: Solve $\tan x = \sin x$ for $0 \le x \le 2 \pi.$  Enter all the solutions, separated by commas.
    Predicted answer: 0, \pi
    Expected answer: 0,\pi,2\pi.

    Reasoning: Number of solutions is different.
    Judgement: No


    YOUR TASK

    Problem: {problem}
    Predicted answer: {predicted_answer}
    Expected answer: {expected_answer}
