name: GPU tests

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, labeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gpu-tests:
    runs-on: self-hosted-nemo-skills
    if: ${{ github.event.label.name == 'run GPU tests' }}
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ github.run_id }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd ${{ github.run_id }}
        python -m pip install --upgrade pip
        pip install .
        pip install -r datasets/requirements.txt
        pip install pytest pytest-cov pytest-timeout
        python datasets/prepare.py
    - name: Run GPU tests
      timeout-minutes: 120
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        cd ${{ github.run_id }}
        nvidia-smi
        export NEMO_SKILLS_CONFIG=cluster_configs/local.yaml
        set -o pipefail # this will make sure next line returns non-0 exit code if tests fail
        ./tests/gpu-tests/run.sh /mnt/datadrive/nemo-skills-data/Meta-Llama-3-8B /mnt/datadrive/nemo-skills-data/Meta-Llama-3-8B-Instruct
